# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_auto_20181222_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
