# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_auto_20181222_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_subscribed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
