# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora', '0007_auto_20181222_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answers',
            name='votes',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
