# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0009_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('link', 'link'), ('post', 'post')], default='post', max_length=10),
        ),
    ]
