# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0010_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='starter',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users_subscribed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
